name: Pull request linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  checktitle:
    name: PR title linter
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            Pull request title "{title}" doesn't match the conventional commit format.