name: Cypress Tests

on:
  pull_request:
    types: [review_requested, ready_for_review]
    branches: [main]

jobs:
  cypress-e2e-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: E2E Tests
        uses: cypress-io/github-action@v5
        with:
          wait-on: http://localhost:5173
          start: npx vite --host
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-component-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Component run
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypress/component
          component: true
